# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-07 11:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20160607_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='availableDate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='publishedDate',
            field=models.DateTimeField(null=True),
        ),
    ]
