# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 01:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20160607_1118'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='watched_date',
            field=models.DateTimeField(null=True),
        ),
    ]
